[advisories]
yanked = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "MIT",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
